### PR TITLE
Auto get eid and fp

### PR DESCRIPTION
**Pull request by huanghyw**
自动获取eid和fp，如果获取失败，使用配置文件中的配置

### CODE REVIEW

**Comment by ZRT-1998** [comment]
=> ERROR [4/5] RUN set -ex;     ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime       && echo Asia/Sh  183.8s

**Comment by ZRT-1998** [comment]
docker构建失败

**Comment by ZRT-1998** [comment]
#9 120.7 + python -c import asyncio;                from pyppeteer import launch;                asyncio.get_event_loop()                    .run_until_complete(launch(args=["--no-sandbox", "--disable-setuid-sandbox"]))
#9 120.8 Traceback (most recent call last):
#9 120.8   File "<string>", line 1, in <module>
#9 120.8 ModuleNotFoundError: No module named 'pyppeteer'

**Comment by ZRT-1998** [comment]
docker构建失败2

**Comment by ZRT-1998** [comment]
lxml==4.6.2
pyppeteer2~=0.2.3

**Comment by ZRT-1998** [comment]
找不到的请提升版本

**Comment by ZRT-1998** [comment]
# clone jd seckill code.
      git clone -b $GIT_BRANCH https://github.com/huanghyw/jd_seckill.git /app; \
      cd /app \

**Comment by ZRT-1998** [comment]
能不能改成从本地克隆

**Comment by huanghyw** [comment]
因为还没有合并到master，想测试的同学讲dockerfile中指定的分支切换到当前这个分支

**Comment by huanghyw** [comment]
合并之前代码还需要整理下，目前功能我这测试没啥问题，大家也可以先测测

**Comment by ZRT-1998** [comment]
#9 29.61 + git clone -b master https://github.com/huanghyw/jd_seckill/tree/auto_get_eid_and_fp.git /app
#9 29.61 Cloning into '/app'...
#9 31.54 fatal: repository 'https://github.com/huanghyw/jd_seckill/tree/auto_get_eid_and_fp.git/' not found

**Comment by huanghyw** [comment]
> 因为还没有合并到master，想测试的同学将dockerfile中指定的分支切换到auto_get_eid_and_fp这个分支

修改dockerfile中$GIT_BRANCH这个变量

**Comment by ZRT-1998** [comment]
#8 39.87 + git clone -b master https://github.com/huanghyw/jd_seckill/tree/auto_get_eid_and_fp /app
#8 39.87 Cloning into '/app'...
#8 56.19 fatal: repository 'https://github.com/huanghyw/jd_seckill/tree/auto_get_eid_and_fp/' not found

**Comment by ZRT-1998** [comment]
https://github.com/huanghyw/jd_seckill/tree/auto_get_eid_and_fp

**Comment by ZRT-1998** [comment]
建议改成本地克隆

**Comment by huanghyw** [comment]
> 建议改成本地克隆

不能改成本地，最新代码都在master上面

**Comment by huanghyw** [comment]
先合并了，整理完代码了再合一版。
目前功能是正常可用的。

**Comment by cuisongliu** [comment]
```
[W:pyppeteer.chromium_downloader] start chromium download.
Download may take a few minutes.
2021-01-03 12:55:03,298 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
2021-01-03 12:56:14,929 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError(60, 'Operation timed out'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
2021-01-03 12:56:15,056 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip

```

mac环境下

**Comment by flyhong666** [comment]
自动获取不了eid和fp。。。
2021-01-03 15:07:12,187 - 11416-MainThread - D:\DownLoad\jd_seckill-master\jd_seckill\jd_spider_requests.py[line:352] - INFO: 自动获取JdTdudfp发生异常，将从配置文件读取！

**Comment by flyhong666** [comment]
不同浏览器得到的eid和fp 都不一样，这个填上去有没有啥影响？

**Comment by huanghyw** [comment]
> ```
> [W:pyppeteer.chromium_downloader] start chromium download.
> Download may take a few minutes.
> 2021-01-03 12:55:03,298 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
> 2021-01-03 12:56:14,929 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError(60, 'Operation timed out'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
> 2021-01-03 12:56:15,056 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
> ```
> 
> mac环境下

下载chromium超时了，多试几次

**Comment by pocketChao** [comment]
大佬问下  抢购失败，无法获取生成订单的基本信息，接口返回:【抢购失败，返回信息:null】这个正常嘛  能回复下嘛谢谢哈

**Comment by EraserKing** [comment]
> 
> 
> > ```
> > [W:pyppeteer.chromium_downloader] start chromium download.
> > Download may take a few minutes.
> > 2021-01-03 12:55:03,298 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
> > 2021-01-03 12:56:14,929 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', TimeoutError(60, 'Operation timed out'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
> > 2021-01-03 12:56:15,056 - 87387-MainThread - /Library/Python/3.7/site-packages/urllib3/connectionpool.py[line:750] - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)'))': /chromium-browser-snapshots/Mac/588429/chrome-mac.zip
> > ```
> > 
> > 
> > mac环境下
> 
> 下载chromium超时了，多试几次

可以设置环境变量，puppeteer_download_host的值为https://npm.taobao.org/mirrors，使用淘宝源，下载很快

不过这个自动获取JdTdudfp的功能好像不能用？我这边是_JdTdudfp是一个Object，看不到Eid和Fp了
反而，有一个变量叫_JdEid，两个变量，一个叫_jdfp_canvas_md5，一个叫_jdfp_webgl_md5，我猜前者是原来的Eid，但是后者不知道哪个对应的是Fp了

**Comment by g1ee** [comment]
> 
> 
> 自动获取eid和fp，如果获取失败，使用配置文件中的配置

大佬。京东秒杀的插件失效了吗。

**Comment by jimsds** [comment]
大佬克隆镜像时报这个错怎么解决啊
image

**Pull request merged**
